### ISSUE TITLE
git-to-s3에서 허용되지 않은 ip 오류 발생

### ISSUE THREAD

**Issue by ghost** [kookmin-sw/2018-cap1-6#16]
[2018-03-23 14:36:32,916][ERROR] Source IP 192.30.252.36 is not allowed
Source IP 192.30.252.36 is not allowed: Exception
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 158, in lambda_handler
raise Exception('Source IP %s is not allowed' % event['context']['source-ip'])
Exception: Source IP 192.30.252.36 is not allowed

우리 팀 repository에 대해서 이런 오류 발생.
어디에서 ip를 허용할 수 있을까?

**Comment by zesow** [comment]
master가 아닌 branch에서는 정상 작동.. 차이가 뭘까

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/14235802/37977249-561a9f7e-321e-11e8-8aba-caabed551dcd.png)
설정에 이 창이 있는데, 현재는 default 상태로 놔두었다. 
131.103.20.160/27,165.254.145.0/26,104.192.143.0/24
이렇게만 허용되어 있는데, 이 이슈의 문제는 위 IP를 허용 안 해줘서 발생하는 것 같다.
위의 ip를 허용하려면 어떻게 표현해야 할까?

**Comment by ghost** [comment]
https://api.github.com/meta
여기서 hook 부분 허용되는 ip 추가해줌으로서 해결.
