### ISSUE TITLE
Git에서 일어나는 변경사항을 alert해주는 API 찾기

### ISSUE THREAD

**Issue by hohyunjun** [kookmin-sw/2018-cap1-6#2]
AWS Lambda를 실행시키는 Signal을 보낼 수 있도록 하는 API 찾기

**Comment by ghost** [comment]
https://developer.github.com/webhooks/
공부 중.

**Comment by hohyunjun** [comment]
## Webhook?
Webhook은 GitHub에서 일어나는 특정 이벤트를 구독하여, 이 이벤트가 일어날 경우 HTTP POST payload를 Webhook에서 설정된 URL로 보내는 역할을 한다. Webhook은 특정 레포지토리에 설치될 수 있다. 설치된 이후에, 지정된 이벤트가 발생할 때마다 동작한다.  디폴트 값으로, webhook은 push 이벤트만 감지한다. 이외에도, 커밋에 대한 코멘트가 작성되거나 브랜치가 생성, 삭제되는 등의 이벤트를 감지하도록 지시할 수 있다. Webhook의 payload는 이벤트 정보에 따라 format이 다르다. 각각의 이벤트를 위해 documented 된 필드들에 더하여, 누가 이벤트를 실행했는지, 이벤트가 발생한 저장소 등을 포함한다. 
## 사용 제한사항
repository 또는 organization에 webhook을 설치하려면, 관리자 권한이 있어야 한다.
