### ISSUE TITLE
.git만 남겨도 분석이 가능할까?

### ISSUE THREAD

**Issue by ghost** [kookmin-sw/2018-cap1-6#29]
분석이 가능하다면 .git만 남겨두고 다 지워서 용량 줄이기.

**Comment by one10004** [comment]
![image](https://user-images.githubusercontent.com/28583530/38294674-9491daac-3826-11e8-9cd6-484d20388509.png)


.git만 남겨놓은 폴더에서 분석 되는 것을 확인
