### ISSUE TITLE
점수화 회의

### ISSUE THREAD

**Issue by one10004** [kookmin-sw/2018-cap1-6#44]
### Github 사용자가 얼마나 효율적으로 Github를 사용했는지를 점수화할 Rule에 어떤 것이 있을지에 대해 논의한다.

- 각 커밋 별로 너무 적은 코드 변화 수(+10 ~ -10)는 제외
- 사용자가 커밋을 꾸준히 했는지, 한꺼번에 몰아서 했는지
- 한 명이 몇 개의 파일에 기여
- % of changes가 유저 별로 골고루 나누어져 있는가

![image](https://user-images.githubusercontent.com/28583530/39795644-89946896-538c-11e8-8260-99cdb259af5b.png)

**Comment by one10004** [comment]
https://docs.google.com/document/d/1hvZZ18zwPS7vSX5a58qAQ6ySIm6AF7RfoQ86qC2chM0/edit

**Comment by hohyunjun** [comment]
너무 적은 코드 변화수를 보여준다 - 실제 코드 변화를 보여준다.

기간별로 나타내는 것은 trade off가 약하다.

파일 별로 커밋 횟수를 파악해서 순서대로 정렬
 -> 그래프화 해서 평균값과 중간값을 기준으로 점수화한다.
기울기 -1이 기준, 그 아래는 감점, 그 위는 +.

팀원 별 커밋 횟수 파악

이슈 활용에 대한 분석!!
 - 이슈를 만든 사람, 이슈 당 reply되는 커밋 횟수
 - 이슈에서 communication하는 사람 수, reply 수. 얼마나 활발하게 토론이 이루어졌는가. 
 - 이슈 타이틀과 본문의 글자 수 합 +10이하는 제외
 - 이슈가 opened된지 얼마나 되었고, 실제로 tracking이 이루어졌는가.

branch에 대한 분석
