### ISSUE TITLE
git 파일별 커밋 횟수 리스트하기.

### ISSUE THREAD

**Issue by ghost** [kookmin-sw/2018-cap1-6#47]

**Comment by ghost** [comment]
str 형식으로 뽑아오기 완료.

**Comment by ghost** [comment]
dictionary 형식으로 파일이름 - 횟수 저장하기.

**Comment by hohyunjun** [comment]
dictionary 형식으로 파일이름 -횟수 저장 완료
EC2 test/subprotest/2018-cap1-2/commitnumperfile.py 파일에
dic 이라는 이름의 변수에 담는 형태로 저장했음.

![image](https://user-images.githubusercontent.com/28583510/40235841-7658b29e-5ae6-11e8-9d04-66099a9efac0.png)
