### ISSUE TITLE
Git inspector 기능 추가 논의

### ISSUE THREAD

**Issue by one10004** [kookmin-sw/2018-cap1-6#7]
어떤 기능을 추가할지는 추후 논의

**Comment by ghost** [comment]
clone하지 않고, 로컬에 있는 압축파일 풀어서 분석하는 기능.

**Comment by one10004** [comment]
# 1. 로컬 폴더 분석

## 1-1. 메뉴에서 1번 선택
![image](https://user-images.githubusercontent.com/28583530/37695610-ed372e8c-2d13-11e8-840d-3d80498c85a4.png)

## 1-2. 로컬 폴더의 경로 입력
![image](https://user-images.githubusercontent.com/28583530/37695619-f7c41fe0-2d13-11e8-9824-fcdb69ca2b96.png)

## 1-3. 실행 결과
![image](https://user-images.githubusercontent.com/28583530/37695640-1b542ff4-2d14-11e8-89d2-eb386172bd32.png)
-> 클론 과정 없이 분석 진행


# 2. 압축된 로컬 파일 분석

## 2-1. 메뉴에서 2번 선택
![image](https://user-images.githubusercontent.com/28583530/37695743-d0c89d16-2d14-11e8-83d9-f4ca915592ae.png)

## 2-2. 압축파일의 경로와 파일 이름 입력
![image](https://user-images.githubusercontent.com/28583530/37695751-dd1cb78c-2d14-11e8-8aab-0b8fa6420d43.png)

## 2-3. 압축 해제 된 폴더 생성
![image](https://user-images.githubusercontent.com/28583530/37695766-f6a895f4-2d14-11e8-93a7-64851e683ddb.png)

## 2-4. 실행 결과
![image](https://user-images.githubusercontent.com/28583530/37695774-054eeda6-2d15-11e8-9036-1ccc24c77b9c.png)
-> 클론 과정 없이 분석 진행


# 3. Git 주소 분석

## 3-1 메뉴에서 3번 선택
![image](https://user-images.githubusercontent.com/28583530/37695789-3212b03e-2d15-11e8-8adf-b6ddf48c6fe1.png)

## 3-2 Git 주소 입력
![image](https://user-images.githubusercontent.com/28583530/37695795-3c2529f8-2d15-11e8-95e9-b2dc8360a2c7.png)

## 3-3. 실행 결과
-> 이전과 같은 방식으로 클론한 뒤에 분석 진행

**Comment by one10004** [comment]
## git commit message 규칙(영문 기준)
1. 제목과 본문을 한 줄 띄워 분리하기
2. 제목은 영문 기준 50자 이내로
3. 제목 첫글자를 대문자로
4. 제목 끝에 . 금지
5. 제목은 명령조로
6. 본문은 영문 기준 72자마다 줄 바꾸기

- 유저 별 커밋 메시지를 불러와서 위의 규칙을 검사해주는 것이 어떨까?

**Comment by one10004** [comment]
44번 이슈에서 계속
