### ISSUE TITLE
AWS Lambda에 Python Code Packaging 후 결과값 확인하기

### ISSUE THREAD

**Issue by hohyunjun** [kookmin-sw/2018-cap1-6#9]
Python으로 짜여진 Git inspector를 AWS Lambda에 올리기 전에, 간단한 Python 코드를 AWS Lambda에 올려 테스트해 본다.

**Comment by ghost** [comment]
https://youtu.be/hzlxWBs1Qt4
파이썬 패키지하여 Lambda에 올리기 (Makefile)

**Comment by ghost** [comment]
https://serverless.com/blog/serverless-python-packaging/
serverless 프레임워크를 이용한 파이썬 패키징 & 람다에 올리기

**Comment by hohyunjun** [comment]
https://devstarsj.github.io/2017/07/07/Lambda.Deploy.Python/
Lambda와 API Gateway 연동부터 Python Packaging까지
